--A travel booking platform, wants to improve revenue growth, customer retention, and booking conversion. The company currently collects large volumes of user, booking, and transaction data but lacks clear insights into customer behavior, high-value users, pricing effectiveness, and churn patterns.
--This project analyzes customer demographics, booking history, discounts, subscriptions, trip categories, and revenue data to uncover actionable insights and provide data-driven recommendations for business and product strategy.

--Q1.What is the total revenue generated by male vs. female travelers?
SELECT
    gender,
    SUM(GREATEST(final_amount, 0)) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

--Q2.Which users used a discount but still spent more than the average booking value?
WITH avg_booking AS (
    SELECT AVG(GREATEST(final_amount, 0)) AS avg_value
    FROM customer
)
SELECT
    user_id,
    COUNT(*) AS bookings,
    AVG(GREATEST(final_amount, 0)) AS avg_spend
FROM customer, avg_booking
WHERE used_discount = 1
  AND GREATEST(final_amount, 0) > avg_value
GROUP BY user_id
ORDER BY avg_spend DESC;

--Q3.Which are the top 5 destinations with the highest average user ratings?
SELECT
    destination,
    ROUND(AVG(rating)::numeric, 2) AS avg_rating,
    COUNT(*) AS total_reviews
FROM customer
GROUP BY destination
HAVING COUNT(*) >= 20
ORDER BY avg_rating DESC
LIMIT 5;


--Q4.Compare the average booking value between Standard and Premium travel packages.
SELECT
    package_type,
    ROUND(AVG(GREATEST(final_amount, 0)), 2) AS avg_booking_value
FROM customer
GROUP BY package_type;


--Q5.Do subscribed users spend more than non-subscribed users? Compare both average spend and total revenue.
SELECT
    is_subscriber,
    COUNT(*) AS bookings,
    ROUND(AVG(GREATEST(final_amount, 0)), 2) AS avg_spend,
    SUM(GREATEST(final_amount, 0)) AS total_revenue
FROM customer
GROUP BY is_subscriber
ORDER BY total_revenue DESC;


--Q6.Which 5 destinations have the highest percentage of discounted bookings?
SELECT
    destination,
    COUNT(*) AS total_bookings,
    SUM(CASE WHEN used_discount = 1 THEN 1 ELSE 0 END) AS discounted_bookings,
    ROUND(
        100.0 * SUM(CASE WHEN used_discount = 1 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY destination
ORDER BY discount_percentage DESC
LIMIT 5;


--Q7.Segment users into New, Returning, and Loyal travelers based on their total trips and show the count of each segment.
SELECT
    CASE
        WHEN previous_trips = 0 THEN 'New'
        WHEN previous_trips BETWEEN 1 AND 4 THEN 'Returning'
        ELSE 'Loyal'
    END AS user_segment,
    COUNT(DISTINCT user_id) AS users_count
FROM customer
GROUP BY user_segment
ORDER BY users_count DESC;


--Q8.What are the top 3 most booked destinations within each travel category (Adventure, Leisure, Business, Honeymoon, etc.)?
SELECT
    travel_type,
    destination,
    bookings
FROM (
    SELECT
        travel_type,
        destination,
        COUNT(*) AS bookings,
        ROW_NUMBER() OVER (
            PARTITION BY travel_type
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY travel_type, destination
) ranked
WHERE rn <= 3
ORDER BY travel_type, bookings DESC;


--Q9.Are frequent travelers (more than 5 previous trips) more likely to become subscribers?
SELECT
    CASE
        WHEN previous_trips > 5 THEN 'Frequent Traveler'
        ELSE 'Non-Frequent Traveler'
    END AS traveler_type,
    ROUND(AVG(is_subscriber::int) * 100, 2) AS subscription_rate
FROM customer
GROUP BY traveler_type;


--Q10.What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(GREATEST(final_amount, 0)) AS total_revenue,
    ROUND(AVG(GREATEST(final_amount, 0)), 2) AS avg_booking_value
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;





